name: CI


on:
  push:
    branches: [ master ]



jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '16.16.0'

    - run: npm install
    - run: node node_modules/react-scripts/scripts/build.js
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
       FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


